# Generated by Django 5.0.7 on 2024-08-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='home/%Y/%m', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
                'db_table': 'Home',
            },
        ),
    ]
