# Generated by Django 5.0.7 on 2024-08-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Not',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/%Y/%m', verbose_name='image')),
                ('title', models.CharField(max_length=256, verbose_name='name')),
                ('text', models.TextField(max_length=256, verbose_name='text')),
            ],
            options={
                'verbose_name': 'Not',
                'verbose_name_plural': 'Nots',
                'db_table': 'Not',
            },
        ),
    ]
