# Generated by Django 5.0.7 on 2024-08-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_not'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/%Y/%m', verbose_name='image')),
                ('text', models.TextField(verbose_name='text')),
                ('name_position', models.CharField(max_length=256, verbose_name='position')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'Image',
            },
        ),
        migrations.AlterField(
            model_name='not',
            name='image',
            field=models.ImageField(upload_to='not/%Y/%m', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='not',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='not',
            name='title',
            field=models.CharField(max_length=256, verbose_name='title'),
        ),
    ]
