# Generated by Django 5.0.7 on 2024-08-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_image_alter_not_image_alter_not_text_alter_not_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/%Y/%m', verbose_name='image')),
                ('text', models.TextField(verbose_name='text')),
                ('about', models.CharField(max_length=256, verbose_name='about')),
                ('boss_first_name', models.TextField(max_length=256, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Useful',
                'verbose_name_plural': 'Usefuls',
                'db_table': 'Useful',
            },
        ),
    ]
