# Generated by Django 5.0.7 on 2024-08-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_useful'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useful',
            name='boss_first_name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
    ]
