# Generated by Django 5.0.7 on 2024-08-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_useful_boss_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/%Y/%m', verbose_name='image')),
                ('number_of_project', models.IntegerField(max_length=256, verbose_name='project')),
                ('category_of_project', models.CharField(max_length=256, verbose_name='category')),
            ],
            options={
                'verbose_name': 'All',
                'verbose_name_plural': 'Alls',
                'db_table': 'All',
            },
        ),
    ]
